# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{frac}
  s.version = "0.9.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pavel Valodzka"]
  s.date = %q{2011-06-19}
  s.email = %q{pavel@valodzka.name}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "VERSION",
    "ext/extconf.rb",
    "ext/frac_ext.c",
    "frac.gemspec",
    "lib/frac.js",
    "lib/frac.rb",
    "test/frac_test.html",
    "test/frac_test.rb"
  ]
  s.homepage = %q{https://github.com/valodzka/frac}
  s.licenses = [""]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Find rational approximation to given real number.  Based on the theory of continued fractions  if x = a1 + 1/(a2 + 1/(a3 + 1/(a4 + ...)))  then best approximation is found by truncating this series (with some adjustments in the last term). Note the fraction can be recovered as the first column of the matrix  ( a1 1 ) ( a2 1 ) ( a3 1 ) ... ( 1  0 ) ( 1  0 ) ( 1  0 )  Instead of keeping the sequence of continued fraction terms, we just keep the last partial product of these matrices.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

